version: '3.8'
services:
  n8n-mcp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - USE_FIXED_HTTP=true
      - MCP_MODE=http
      - PORT=3000
      - N8N_BASE_URL=${N8N_BASE_URL}
      - N8N_API_KEY=${N8N_API_KEY}
    restart: unless-stopped
